
export const terms = [
    { term: "Abhyasa", definition: "Consistent and dedicated practice." },
    { term: "Adho Mukha Svanasana", definition: "Downward-Facing Dog pose." },
    { term: "Agni", definition: "The digestive fire in Ayurveda; also related to inner fire and transformation." },
    { term: "Ahamkara", definition: "The ego or the sense of 'I-ness'." },
    { term: "Ahimsa", definition: "Non-harming and non-violence in thought, word, and deed. The first of the Yamas." },
    { term: "Ajna Chakra", definition: "The third-eye chakra, located between the eyebrows, related to intuition, insight, and perception." },
    { term: "Akasha", definition: "Ether or space, the first of the five great elements (pancha mahabhutas)." },
    { term: "Anahata Chakra", definition: "The heart chakra, located at the center of the chest, associated with love, compassion, connection, and well-being." },
    { term: "Ananda", definition: "Bliss, divine joy, or a state of profound well-being." },
    { term: "Aparigraha", definition: "Non-possessiveness or non-grasping, the fifth of the Yamas." },
    { term: "Ardha", definition: "Half. Often used as a prefix for pose names, like Ardha Chandrasana (Half Moon Pose)." },
    { term: "Asana", definition: "A physical posture or pose in yoga. The third limb of Ashtanga yoga." },
    { term: "Ashram", definition: "A spiritual hermitage or monastery." },
    { term: "Ashtanga", definition: "Literally 'eight limbs.' A specific, physically demanding style of yoga, or referring to the eight limbs of yoga described by Patanjali." },
    { term: "Asteya", definition: "Non-stealing, the third of the Yamas." },
    { term: "Atman", definition: "The true Self or eternal soul." },
    { term: "Avidya", definition: "Ignorance or misconception; the root cause of suffering in yogic philosophy." },
    { term: "Ayurveda", definition: "The traditional Hindu system of medicine, based on the idea of balance in bodily systems." },
    { term: "Baddha", definition: "Bound. Often used in pose names like Baddha Konasana (Bound Angle Pose)." },
    { term: "Bandha", definition: "An energetic body lock used to control and direct prana (life force energy)." },
    { term: "Bhakti Yoga", definition: "The path of devotion; one of the main paths of yoga." },
    { term: "Bhagavad Gita", definition: "An ancient Indian scripture that is a key text of Hinduism and yoga philosophy, detailing a conversation between Prince Arjuna and the god Krishna." },
    { term: "Bija Mantra", definition: "A seed sound or syllable used to activate the chakras (e.g., Lam for Muladhara)." },
    { term: "Bodhi", definition: "Enlightenment or awakening." },
    { term: "Brahman", definition: "The ultimate reality or the absolute, supreme spirit in Hinduism." },
    { term: "Brahmacharya", definition: "Moderation or right use of energy; the fourth of the Yamas." },
    { term: "Buddhi", definition: "The intellect, faculty of reason, and decision-making." },
    { term: "Chakra", definition: "Energy centers in the subtle body. There are seven main chakras along the spine." },
    { term: "Chandra", definition: "Moon. Used in Chandra Namaskar (Moon Salutation)." },
    { term: "Chaturanga Dandasana", definition: "Four-Limbed Staff Pose, a yoga push-up." },
    { term: "Chitta", definition: "The mind-stuff or consciousness, which includes thoughts, emotions, and memories." },
    { term: "Darshana", definition: "A philosophical viewpoint or system of thought." },
    { term: "Deva/Devi", definition: "A male/female deity or divine being." },
    { term: "Dharana", definition: "Concentration, the sixth limb of Ashtanga yoga." },
    { term: "Dharma", definition: "One's duty, purpose, or path in life." },
    { term: "Dhyana", definition: "Meditation, the seventh limb of Ashtanga yoga." },
    { term: "Dosha", definition: "In Ayurveda, the three energies (Vata, Pitta, Kapha) believed to circulate in the body and govern physiological activity." },
    { term: "Drishti", definition: "A focused gaze used during asana practice to cultivate concentration and inner focus." },
    { term: "Dukkha", definition: "Suffering, dissatisfaction, or pain." },
    { term: "Eka", definition: "One. Often used as a prefix in pose names, like Eka Pada Rajakapotasana (One-Legged King Pigeon Pose)." },
    { term: "Gunas", definition: "The three fundamental qualities of nature: Sattva (purity, balance), Rajas (activity, passion), and Tamas (inertia, darkness)." },
    { term: "Guru", definition: "A spiritual teacher who dispels darkness (ignorance) and leads a student toward enlightenment." },
    { term: "Hatha", definition: "A general term for the physical practice of yoga. 'Ha' means sun and 'tha' means moon, representing the balance of opposing energies." },
    { term: "Ida Nadi", definition: "The subtle energy channel associated with the left side of the body, the moon's cooling energy, and the parasympathetic nervous system." },
    { term: "Ishvara", definition: "The Supreme Being, a personal god, or the divine consciousness." },
    { term: "Ishvara Pranidhana", definition: "Surrender to a higher power or the divine, the fifth of the Niyamas." },
    { term: "Jalandhara Bandha", definition: "The throat lock, one of the main bandhas, which involves tucking the chin to the chest." },
    { term: "Japa", definition: "The meditative repetition of a mantra." },
    { term: "Jivamukti", definition: "A modern style of yoga that incorporates vinyasa flow with spiritual teachings, chanting, and ethical principles." },
    { term: "Jnana Yoga", definition: "The path of knowledge or wisdom, which involves study and self-inquiry." },
    { term: "Kapalabhati", definition: "Skull-shining breath, a cleansing and energizing pranayama technique involving forceful exhalations." },
    { term: "Kapha", definition: "One of the three doshas in Ayurveda, associated with earth and water elements, governing structure and lubrication." },
    { term: "Karma", definition: "The law of cause and effect; the sum of a person's actions and their consequences in this and previous lives." },
    { term: "Karma Yoga", definition: "The path of selfless action, performing duties without attachment to the outcome." },
    { term: "Karuna", definition: "Compassion or mercy." },
    { term: "Kirtan", definition: "A devotional practice of call-and-response chanting, often with musical accompaniment." },
    { term: "Kleshas", definition: "The five 'poisons' or afflictions of the mind that are the cause of suffering: ignorance, ego, attachment, aversion, and clinging to life." },
    { term: "Koshas", definition: "The five 'sheaths' or layers of the self, from the physical body (Annamaya) to the bliss body (Anandamaya)." },
    { term: "Kriya", definition: "A cleansing or purification technique in yoga. In Kundalini yoga, it refers to a specific sequence of actions." },
    { term: "Kumbhaka", definition: "Breath retention in pranayama, which can occur after an inhalation (Antara) or exhalation (Bahya)." },
    { term: "Kundalini", definition: "Dormant spiritual energy often depicted as a coiled serpent at the base of the spine, which can be awakened through yogic practice." },
    { term: "Lila", definition: "Divine play or cosmic dance; the playful nature of the universe." },
    { term: "Malasana", definition: "Garland Pose or a low yogic squat." },
    { term: "Mandala", definition: "A spiritual and ritual symbol in Hinduism and Buddhism, representing the universe. Often used in art and meditation." },
    { term: "Manipura Chakra", definition: "The solar plexus chakra, located at the navel center, associated with personal power, self-esteem, and transformation." },
    { term: "Mantra", definition: "A word, sound, or phrase repeated to aid concentration in meditation." },
    { term: "Maya", definition: "The illusion or deceptive appearance of the material world." },
    { term: "Moksha", definition: "Liberation from the cycle of death and rebirth (samsara); enlightenment." },
    { term: "Mudra", definition: "A symbolic hand gesture used in yoga and meditation to direct energy and consciousness." },
    { term: "Mula Bandha", definition: "The root lock, an energetic lock involving the engagement of the pelvic floor muscles." },
    { term: "Muladhara Chakra", definition: "The root chakra, located at the base of the spine, associated with grounding, stability, and survival instincts." },
    { term: "Nadi", definition: "Subtle energy channels in the body through which prana (life force) flows. There are said to be 72,000 nadis." },
    { term: "Nadi Shodhana", definition: "Alternate nostril breathing, a pranayama technique for balancing the left and right hemispheres of the brain and calming the nervous system." },
    { term: "Namaste", definition: "A respectful greeting often used at the beginning and end of a yoga class, meaning 'the divine in me bows to the divine in you'." },
    { term: "Neti", definition: "A nasal cleansing kriya, often performed with a neti pot." },
    { term: "Niyamas", definition: "The five observances or internal disciplines in yoga: purity (Saucha), contentment (Santosha), self-discipline (Tapas), self-study (Svadhyaya), and surrender (Ishvara Pranidhana)." },
    { term: "Ojas", definition: "The subtle essence of vitality and immunity in Ayurveda." },
    { term: "Om", definition: "A sacred sound and spiritual icon, considered the primordial sound of the universe. Chanted to connect with the divine." },
    { term: "Pada", definition: "Foot or leg." },
    { term: "Padma", definition: "Lotus. Used in Padmasana (Lotus Pose)." },
    { term: "Parivrtta", definition: "Revolved or twisted." },
    { term: "Patanjali", definition: "The sage who compiled the Yoga Sutras, a foundational text of classical yoga philosophy, around 400 CE." },
    { term: "Pingala Nadi", definition: "The subtle energy channel associated with the right side of the body, the sun's heating energy, and the sympathetic nervous system." },
    { term: "Pitta", definition: "One of the three doshas in Ayurveda, associated with fire and water elements, governing metabolism and transformation." },
    { term: "Pooja", definition: "A ritual of worship or offering to a deity." },
    { term: "Prakriti", definition: "The essential nature of matter or the primal creative force; the feminine aspect of creation." },
    { term: "Prana", definition: "Life force energy that flows through all living things. It is the vital energy that sustains body and mind." },
    { term: "Pranidhana", definition: "Surrender or devotion." },
    { term: "Pranayama", definition: "The practice of breath control in yoga. The fourth limb of Ashtanga yoga." },
    { term: "Prasada", definition: "A blessed offering, typically food, that has been presented to a deity." },
    { term: "Pratyahara", definition: "Withdrawal of the senses from external distractions, the fifth limb of Ashtanga yoga." },
    { term: "Purusha", definition: "The pure, eternal consciousness or the true Self; the masculine, unchanging aspect of reality." },
    { term: "Raja Yoga", definition: "The 'royal path' of yoga, often synonymous with the Ashtanga system of Patanjali, focusing on mastery of the mind." },
    { term: "Rajas", definition: "One of the three gunas, representing activity, passion, change, and movement." },
    { term: "Sadhana", definition: "A dedicated spiritual practice, often performed daily." },
    { term: "Sahasrara Chakra", definition: "The crown chakra, located at the top of the head, associated with spiritual connection, enlightenment, and unity." },
    { term: "Samadhi", definition: "A state of profound meditative absorption where the self merges with the object of meditation; the final limb of Ashtanga yoga." },
    { term: "Samsara", definition: "The cycle of death and rebirth to which life in the material world is bound, driven by karma." },
    { term: "Samskara", definition: "Mental impressions or psychological imprints left by past experiences, which influence present behavior." },
    { term: "Sankalpa", definition: "An intention or resolve made during yogic practice, often at the beginning of Yoga Nidra." },
    { term: "Santosha", definition: "Contentment, the second of the Niyamas." },
    { term: "Satya", definition: "Truthfulness in thought, word, and deed, the second of the Yamas." },
    { term: "Sattva", definition: "One of the three gunas, representing purity, harmony, balance, and light." },
    { term: "Saucha", definition: "Purity or cleanliness of body, mind, and speech, the first of the Niyamas." },
    { term: "Savasana", definition: "Corpse Pose, the final resting pose in a yoga class, intended for deep relaxation and integration." },
    { term: "Seva", definition: "Selfless service performed without any expectation of result or reward." },
    { term: "Shakti", definition: "The divine feminine creative power, energy, and dynamic force that moves through the universe." },
    { term: "Shanti", definition: "Peace. Often chanted three times to represent peace in body, mind, and spirit." },
    { term: "Shishya", definition: "A disciple or student of a guru." },
    { term: "Shiva", definition: "A principal deity of Hinduism, representing the destroyer, transformer, and the pure consciousness (Purusha)." },
    { term: "Sitali", definition: "Cooling breath, a pranayama technique involving curling the tongue to inhale." },
    { term: "Sthira", definition: "Steadiness and stability, a quality to be cultivated in asana practice." },
    { term: "Sukha", definition: "Ease, comfort, or happiness. A quality to be cultivated in asana practice, balancing Sthira." },
    { term: "Surya", definition: "Sun. Used in Surya Namaskar (Sun Salutation)." },
    { term: "Sushumna Nadi", definition: "The central energy channel that runs along the spine, through which Kundalini energy is said to rise." },
    { term: "Sutra", definition: "A thread or aphorism. The Yoga Sutras are a collection of 196 such aphorisms." },
    { term: "Svadhisthana Chakra", definition: "The sacral chakra, located in the lower abdomen, associated with creativity, emotion, and pleasure." },
    { term: "Svadhyaya", definition: "Self-study or study of sacred texts, the fourth of the Niyamas." },
    { term: "Tadasana", definition: "Mountain Pose, the foundation for all standing poses." },
    { term: "Tamas", definition: "One of the three gunas, representing inertia, darkness, inactivity, and heaviness." },
    { term: "Tantra", definition: "A spiritual tradition that uses the body and its energies to achieve enlightenment, emphasizing the union of the divine masculine (Shiva) and feminine (Shakti)." },
    { term: "Tapas", definition: "Self-discipline, austerity, or the inner fire of transformation, the third of the Niyamas." },
    { term: "Tejas", definition: "The subtle essence of fire element, governing intelligence and radiance." },
    { term: "Trikonasana", definition: "Triangle Pose." },
    { term: "Trataka", definition: "A yogic cleansing technique and meditation involving gazing at a fixed point, usually a candle flame." },
    { term: "Uddiyana Bandha", definition: "The upward abdominal lock, an energetic lock performed by drawing the abdomen in and up." },
    { term: "Ujjayi", definition: "Victorious breath, a pranayama technique that creates a soft, audible sound in the back of the throat, used to build heat and focus." },
    { term: "Upanishads", definition: "Ancient Sanskrit texts of spiritual teaching and ideas of Hinduism, which form the philosophical foundation of yoga." },
    { term: "Upavistha", definition: "Seated." },
    { term: "Utkata", definition: "Fierce or powerful. Used in Utkatasana (Chair Pose)." },
    { term: "Uttana", definition: "Intense stretch." },
    { term: "Vairagya", definition: "Detachment or renunciation of worldly desires." },
    { term: "Vata", definition: "One of the three doshas in Ayurveda, associated with air and ether elements, governing movement and the nervous system." },
    { term: "Vayus", definition: "The five 'winds' or currents of prana that govern different functions in the body (Prana, Apana, Samana, Udana, Vyana)." },
    { term: "Vedas", definition: "The most ancient Hindu scriptures, containing hymns, philosophy, and guidance on ritual." },
    { term: "Vinyasa", definition: "A style of yoga characterized by stringing postures together so that you move from one to another, seamlessly, using breath." },
    { term: "Viparita", definition: "Inverted." },
    { term: "Virabhadrasana", definition: "Warrior Pose." },
    { term: "Vishuddha Chakra", definition: "The throat chakra, associated with communication, self-expression, and purification." },
    { term: "Vritti", definition: "Fluctuations or modifications of the mind; mental chatter." },
    { term: "Yamas", definition: "The five ethical principles or moral restraints in yoga: non-harming (Ahimsa), truthfulness (Satya), non-stealing (Asteya), moderation (Brahmacharya), and non-possessiveness (Aparigraha)." },
    { term: "Yantra", definition: "A mystical diagram, often geometric, used in meditation to focus the mind and represent divine energy." },
    { term: "Yoga", definition: "From the Sanskrit root 'yuj,' meaning to yoke or unite. A system of practices for uniting mind, body, and spirit." },
    { term: "Yoga Nidra", definition: "Yogic sleep; a state of conscious deep sleep for profound relaxation and healing, typically guided." },
    { term: "Yogi/Yogini", definition: "A male/female practitioner of yoga." },
    { term: "Yuga", definition: "An era or epoch within a four-age cycle in Hindu cosmology." }
];
