
export const videos = [
  { 
    slug: 'advanced-yoga-workshop',
    title: 'Advanced Yoga Workshop',
    description: 'Deepen your practice with advanced techniques.',
    longDescription: 'This workshop is designed for experienced yogis looking to take their practice to the next level. We will break down complex poses and transitions, focusing on alignment, strength, and flexibility.',
    videoUrl: 'https://storage.googleapis.com/studioprod-5112a-assets/assets/pranian/video-meditation-1.m3u8',
    posterUrl: 'https://images.unsplash.com/photo-1730890754666-fbffee87d65b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHx2aWRlbyUyMGxlc3NvbnxlbnwwfHx8fDE3NjQwMDEwMDJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageId: 'product-video',
    author: 'Pranian Wellness',
    duration: '01:15:00',
  },
  { 
    slug: 'meditation-for-beginners-series',
    title: 'Meditation for Beginners Series',
    description: 'A guided introduction to mindfulness.',
    longDescription: 'New to meditation? This series is for you. We will gently guide you through the basics of mindfulness, helping you build a consistent and rewarding practice from the ground up.',
    videoUrl: 'https://storage.googleapis.com/studioprod-5112a-assets/assets/pranian/video-meditation-2.m3u8',
    posterUrl: 'https://images.unsplash.com/photo-1617994422026-1ee4a32e3a65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxyZWxheGluZyUyMGJyZWF0aHxlbnwwfHx8fDE3NjQxMTAwMDB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageId: 'product-video',
    author: 'Pranian Wellness',
    duration: '30:00',
  },
  { 
    slug: 'morning-vinyasa-flow',
    title: 'Morning Vinyasa Flow',
    description: 'Energize your day with a dynamic flow.',
    longDescription: 'Start your morning with this energizing 30-minute Vinyasa flow. This class is designed to awaken your body, build heat, and set a positive tone for the day ahead.',
    videoUrl: 'https://storage.googleapis.com/studioprod-5112a-assets/assets/pranian/video-meditation-1.m3u8',
    posterUrl: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxtb3JuaW5nJTIweW9nYXxlbnwwfHx8fDE3MjE4NzYxNzV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageId: 'yoga-1',
    author: 'Pranian Wellness',
    duration: '30:00',
  },
  { 
    slug: 'restorative-yoga-for-relaxation',
    title: 'Restorative Yoga for Relaxation',
    description: 'Unwind and release with this gentle practice.',
    longDescription: 'This 45-minute restorative yoga class uses props to support your body in gentle poses, allowing for deep relaxation and stress release. Perfect for the end of a long day.',
    videoUrl: 'https://storage.googleapis.com/studioprod-5112a-assets/assets/pranian/video-meditation-2.m3u8',
    posterUrl: 'https://images.unsplash.com/photo-1591343395902-1adcb454c4e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxyZXN0b3JhdGl2ZSUyMHlvZ2F8ZW58MHx8fHwxNzIxODc2MjAxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageId: 'yoga-2',
    author: 'Pranian Wellness',
    duration: '45:00',
  },
];
